name: k3s Testing
on:
  push:
    branches:
      - 'fix/**'
      - 'master'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: rohan397/actions-k3s@master
      id: k3s
      with:
        version: 'latest'
    - run: |
        kubectl get nodes

